### ISSUE TITLE
I2C over hard-coded /dev/i2c-1 not working

### ISSUE THREAD

**Issue by ugate** [sandeepmistry/node-chip-io#11]
I tested a PCA9685 with chip-io (master branch) and noticed that nothing was happening using the [johnny-five example](http://johnny-five.io/examples/servo-PCA9685/). It looks like [errors are just consumed in i2c.js](/sandeepmistry/node-chip-io/blob/master/lib/chip-io.js#L203) so there's no way of knowing unless debugging (headless chip, used `node --inspect` flag with devtools from remote PC). Maybe a better approach when encountering errors would be to emit an `error` event instead of throwing or ignoring? I noticed that `chip-io.js` uses a hard-coded **1** for the bus value in `/dev/i2c-1` [here](/sandeepmistry/node-chip-io/blob/master/lib/chip-io.js#L193) and [here](/sandeepmistry/node-chip-io/blob/master/lib/chip-io.js#L245), but a `ls /dev` only shows `i2c-0` and `i2c-2` (Linux 4.4.11-ntc). 

@rwaldron I'm trying to understand what the proper way to pass in the bus identifier when using the [johnny-five API](http://johnny-five.io/api/board/#i2cconfigmilliseconds)/`Board.i2c` functions for boards that support more than one I2C bus?

**Comment by rwaldron** [comment]
Platform specific `bus` property support needs to be handled by the IO Plugin—all Johnny-Five does is forward the options passed to the component class constructor, through to the the `i2cConfig(...)` call.

**Comment by rwaldron** [comment]
What version of Node.js is on the Chip?

**Comment by rwaldron** [comment]
nvm, I see that this project points to the nodesource install instructions—very smart.

**Comment by rwaldron** [comment]
I just found this: https://github.com/xtacocorex/CHIP_IO/issues/11

**Comment by rwaldron** [comment]
@ugate [This should allow you to specify the bus](https://github.com/sandeepmistry/node-chip-io/pull/12) as shown in the following:

```js
var a = new five.Servo({
  bus: 1,
  address: 0x40,
  controller: "PCA9685",
  pin: 0,
});
```

**Comment by ugate** [comment]
@rwaldron Thanks for the update! I noticed the same thing on #9. What threw me off is the docs that state that `Board.i2cConfig([milliseconds])` takes [an optional millisecond parameter rather than an object of options](http://johnny-five.io/api/board/#i2cconfigmilliseconds). Should the docs be updated to reflect an options object instead?

**Comment by sandeepmistry** [comment]
@ugate it would be awesome if you could submit a pull request to the Johnny Five docs your `Board.i2cConfig([milliseconds])` observation.

**Comment by ugate** [comment]
@sandeepmistry [done](/rwaldron/io-plugins#11) :+1:
