### ISSUE TITLE
PWM0 appears to implement range incorrectly

### ISSUE THREAD

**Issue by jmaxxz** [sandeepmistry/node-chip-io#21]
Tested using a led between pwm0 (18) and GND

```javascript
led.off(); //turned on the led
led.on(); //turned off the led
led.brightness(0); // turned on led
led.brightness(255) // turned off led
```

it should also be noted that when the led is "off" it is not off, just dim.

LED api: http://johnny-five.io/api/led/

**Comment by jmaxxz** [comment]
Example with output from oscilloscope
```javascript
const five = require('johnny-five');
const chipio = require('chip-io');

var board = new five.Board({
  io: new chipio()
});

board.on('ready', function() {
  var led = new five.Led(18);
  led.on();
});

```

![hantek343_3](https://cloud.githubusercontent.com/assets/828153/19178665/6c6c1234-8c44-11e6-98d0-98e141262e60.png)

**Comment by rwaldron** [comment]
Looks inverted! I wonder if the PWM channel polarity needs to be flipped?

**Comment by sandeepmistry** [comment]
I've flipped the PWM polarity in https://github.com/sandeepmistry/node-chip-io/commit/8afcb5389418fabea50e192e750e74cf4ec165ff. @jmaxxz please try the change out via `npm install sandeepmistry/node-chip-io`.

**Comment by jmaxxz** [comment]
Will try it out tonight.

**Comment by jmaxxz** [comment]
Works much better!  However, on is not fully on, the waveform in the scope screenshot has been inverted with this change.

**Comment by sandeepmistry** [comment]
@jmaxxz thanks for trying it out!

> However, on is not fully on, the waveform in the scope screenshot has been inverted with this change.

Could you please open a new issue to track this. For 0 and 255, I think we need to disable PWM and switch to normal GPIO mode ...
