### ISSUE TITLE
LCD example

### ISSUE THREAD

**Issue by norgeous** [sandeepmistry/node-chip-io#39]
If the examples shown at https://github.com/sandeepmistry/node-chip-io/pull/19 are working and relevant, could they be included in the `/examples/` folder? Sorry for the open / close / reopen...

**Comment by norgeous** [comment]
nvm, those are for chip-io...

**Comment by sandeepmistry** [comment]
Why do you think the examples would be valuable? We can't repeat all of the J5 examples in this repo.

**Comment by norgeous** [comment]
fair point. looking at the  [j5 examples](http://johnny-five.io/examples/) there are too many to replicate...
