### ISSUE TITLE
No nodes work

### ISSUE THREAD

**Issue by ThanhTungNguyen** [sandeepmistry/node-chip-io#52]
I tried to install node-red-contrib-gpio, chip-io and johnny-five on my C.h.i.p. But when I load the node-red from the browser, all the nodes for gpio grey and can't use.
There is no way to enable them. 
node v6.11.0
npm v5.0.3
node-red v0.16.2

**Comment by fivdi** [comment]
I'm not 100% sure but my gut feeling tells me that https://github.com/monteslu/node-red-contrib-gpio is a better place for this issue. On the other maybe @monteslu can help out here.

**Comment by sandeepmistry** [comment]
@ThanhTungNguyen please see @fivdi's suggestion above and open an issue in the following repo: https://github.com/monteslu/node-red-contrib-gpio.
