### ISSUE TITLE
Possible to support stepper motors?

### ISSUE THREAD

**Issue by Torsten85** [sandeepmistry/node-chip-io#53]
Hey there... is it possible to drive a stepper motor with johnny five and chip? I've several stepper motors (Nema 17) and drivers (DRV8825) here but no clue how to get them moving... the comment in the johnny.Stepper class shows that this is only supported for arduino board.

Thanks in advance

**Comment by sandeepmistry** [comment]
I would say no, https://github.com/rwaldron/johnny-five/wiki/Stepper - looks like it's firmata based.
