### ISSUE TITLE
analogRead is not a function

### ISSUE THREAD

**Issue by ohpauleez** [sandeepmistry/node-chip-io#54]
First and foremost, thank you for all the effort you've put into this project.

When hooking up an FSR to the chip, I reached for J5's generic Sensor type (same general setup as found [in the docs](http://johnny-five.io/examples/sensor-fsr/)) - plugged into XIO-P0 and the setup like `let fsr = new five.Sensor({pin: "XIO-P0", freq: 25});`.

This results in error, "TypeError: this._chips[pinData.chip].analogRead is not a function" coming from [here](https://github.com/sandeepmistry/node-chip-io/blob/master/lib/chip-io.js#L139), triggered by J5's sensor support -- `johnny-five/lib/sensor.js:104`.

Any thoughts on why this might be happening?  Anything I can do to help out?  Need any additional information?

I'm using Node 8, latest versions of chio-io and johnny-five, kernel 4.4 GUI, and I have the first generation CHIP (with the 4Gb Flash).

**Comment by rwaldron** [comment]
[According to the readme](https://github.com/sandeepmistry/node-chip-io#pin-guide) there is only one pin that supports Analog input: `LRADC`

**Comment by ohpauleez** [comment]
Gah, thanks @rwaldron!  Sorry about the noise.  Works like a charm.

If there's anything I can ever do to help out this project or J5, please reach out!

**Comment by rwaldron** [comment]
No problem ❤️
